const RECEIVE_STOCK_DETAILS = 'RECEIVE_STOCK_DETAILS';
const REQUEST_STOCK_DETAILS = 'REQUEST_STOCK_DETAILS';
const RECEIVE_CHART = 'RECEIVE_CHART';
export { RECEIVE_STOCK_DETAILS, REQUEST_STOCK_DETAILS, RECEIVE_CHART };
