const RECEIVE_LISTS_GAINERS = "RECEIVE_LISTS_GAINERS";
const REQUEST_LISTS_GAINERS = "REQUEST_LISTS_GAINERS";

const RECEIVE_LISTS_LOSERS = "RECEIVE_LISTS_LOSERS";
const REQUEST_LISTS_LOSERS = "REQUEST_LISTS_LOSERS";

const RECEIVE_LISTS_IEXVOLUME = "RECEIVE_LISTS_IEXVOLUME";
const REQUEST_LISTS_IEXVOLUME = "REQUEST_LISTS_IEXVOLUME";

const RECEIVE_LISTS_IEXPERCENT = "RECEIVE_LISTS_IEXPERCENT";
const REQUEST_LISTS_IEXPERCENT = "REQUEST_LISTS_IEXPERCENT";

export {
  RECEIVE_LISTS_GAINERS,
  REQUEST_LISTS_GAINERS,
  RECEIVE_LISTS_LOSERS,
  REQUEST_LISTS_LOSERS,
  RECEIVE_LISTS_IEXVOLUME,
  REQUEST_LISTS_IEXVOLUME,
  RECEIVE_LISTS_IEXPERCENT,
  REQUEST_LISTS_IEXPERCENT
};
