const RECEIVE_LISTS_GAINERS = "RECEIVE_LISTS_GAINERS";

const RECEIVE_LISTS_LOSERS = "RECEIVE_LISTS_LOSERS";

const RECEIVE_LISTS_IEXVOLUME = "RECEIVE_LISTS_IEXVOLUME";

const RECEIVE_LISTS_IEXPERCENT = "RECEIVE_LISTS_IEXPERCENT";
const REQUEST_LIST = "REQUEST_LIST";

export {
  RECEIVE_LISTS_GAINERS,
  RECEIVE_LISTS_LOSERS,
  RECEIVE_LISTS_IEXVOLUME,
  RECEIVE_LISTS_IEXPERCENT,
  REQUEST_LIST
};
